all:
    resource: '@AppBundle/Controller/All'
    prefix: /
    type: annotation

admin:
    resource: '@AppBundle/Controller/Admin'
    prefix: /admin
    type: annotation

api:
    resource: '@AppBundle/Controller/Api'
    prefix: /api
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
