security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MODERATOR:    ROLE_USER
        ROLE_ADMIN:        ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_MODERATOR, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: app.handler.login_success
            logout:
                path:   /logout
                success_handler: app.handler.logout_success
            anonymous:  true
            access_denied_handler: app.handler.access_denied

    access_control:

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: ROLE_ADMIN }

        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
