services:
    app.handler.login_success:
        class:  AppBundle\Service\Authentication\Handler\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    app.handler.logout_success:
        class: AppBundle\Service\Authentication\Handler\LogoutSuccessHandler
        arguments:  ['@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    app.handler.access_denied:
        class: AppBundle\Service\AccessDenied\AccessDeniedHandler
        arguments:  ['@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    app.service.email_notification:
        class: AppBundle\Service\EmailNotificationService
        arguments:  ['@mailer', '@doctrine.orm.entity_manager', '@templating.engine.twig']
        public: true

#imports:
#    - { resource: services/service_upload_files.yml }
